language: node_js

node_js:
- "lts/*"
- "node"

os:
- linux
- osx
- windows

addons:
  hosts:
    - admin.localhost
    - api.localhost

jobs:
  allow_failures:
    - os: windows # https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/9#post_10
